{{- if and .Values.elasticsearch.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "output.fullname" . }}-elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
spec:
  elasticsearch:
    host: quickstart-es-http.{{ .Release.Namespace }}
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
{{- end }}