{{- if or .Values.file.enabled (and (not .Values.cloudwatch.enabled) (not .Values.elasticsearch.enabled) (not .Values.kafka.enabled) (not .Values.loki.enabled) (not .Values.minio.enabled) (not .Values.logdna.enabled)) }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "output.fullname" . }}-file
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
spec:
  file:
    path: /tmp/logs/${tag}/%Y/%m/%d.%H.%M
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
{{- end }}