{{- if and .Values.loki.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "output.fullname" . }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
spec:
  loki:
    url: http://loki:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
{{- end }}