{{- if and .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: logging-s3
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
type: Opaque
data:
  accesskey: {{ randAlphaNum 20 | b64enc | quote }}
  secretkey: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}