{{- if and .Values.cloudwatch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: logging-cloudwatch
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.cloudwatch.aws.access_key | b64enc | quote }}
  secretkey: {{ .Values.cloudwatch.aws.secret_key | b64enc | quote }}
{{- end }}
