dependencies:
- name: minio
  version: 8.x.x
  repository: https://helm.min.io/
  condition: minio.enabled

- name: log-generator
  version: 0.1.x
  repository: https://kubernetes-charts.banzaicloud.com/
  condition: logGenerator.enabled
